# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hmassing <hmassing@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2013/11/19 14:16:45 by hmassing          #+#    #+#              #
#    Updated: 2014/01/10 17:33:37 by hmassing         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

NAME = libft.a

FLAGS = -Werror -Wall -Wextra

SRC = ft_atoi.c ft_bzero.c ft_memdel.c ft_strnew.c ft_isalnum.c ft_isalpha.c \
	  ft_isascii.c ft_isdigit.c ft_strclr.c ft_striter.c \
	  ft_isprint.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
	  ft_memmove.c ft_memalloc.c ft_memset.c ft_putchar.c ft_putnbr.c \
	  ft_putstr.c ft_strcat.c ft_striteri.c ft_strmap.c ft_strnequ.c\
	  ft_strchr.c ft_strcmp.c ft_strcpy.c ft_strdup.c ft_strlcat.c ft_strlen.c\
	  ft_strncat.c ft_strncmp.c ft_strncpy.c ft_strnstr.c ft_strrchr.c\
	  ft_strstr.c ft_tolower.c ft_toupper.c ft_strmapi.c ft_strequ.c \
	  ft_strsub.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_itoa.c \
	  ft_putendl.c ft_strsplittoint.c

OBJS = $(SRC:.c=.o)

RM = rm -f

.PHONY: all clean fclean re

all: $(NAME)

%.o: %.c
	gcc -c -o $@ $^

$(NAME): $(OBJS)
	ar -rc $(NAME) $(OBJS)
	ranlib $(NAME)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all
